console.log('loaded USM align :-)');

aligns={}; // master list of align instances
align = function(s1,s2){
    this.seq1 = s1;
    this.seq2 = s2;
    
    this.uid = 'align'+Math.random().toString().slice(2);
    aligns[this.uid]=this;
    this.txt = function(){
        return ('\n'+s1+'\n'+s2+'\n');
    };
    
    this.seqs = function(){
        console.dir(s1);
        console.dir(s2);
    }
    
    // Smith-Waterman (http://en.wikipedia.org/wiki/Smith%E2%80%93Waterman_algorithm)
    
    
    
    
    
    // ---- UI stuff, no science from hereon ----
    
    
    this.UI=function(){ // create User Interface
        var div0 = document.getElementById('USMalign');
        if(!div0){
            div0 = document.createElement('div');
            div0.id = 'USMalign';
            div0.classList.add('container'); // in case bootstrap is available
            document.body.appendChild(div0);
        }
        var div = document.createElement('div');
        div.align=9; // pointer to the align object
        div.id = this.uid;
        div0.appendChild(div);
        div.appendChild(document.createElement('hr'));
        this.div=div; // it can always be found here
        div.textContent = 'Enter or paste 2 sequences: ';
        var demoSeqs = document.createElement('button');demoSeqs.id='demoSeqs';
        div.appendChild(demoSeqs);demoSeqs.textContent="demo seqs";demoSeqs.style.border=0;
        var in1 = document.createElement('textarea');in1.id="in1";
        in1.style.width='100%';in1.style.color='blue';
        var p1 = document.createElement('p');p1.appendChild(in1);div.appendChild(p1);
        var in2 = document.createElement('textarea');
        in2.id="in2";in2.style.width='100%';in2.style.color='blue';
        var p2 = document.createElement('p');p2.appendChild(in2);div.appendChild(p2);
        var smithAlign = document.createElement('button');smithAlign.id='smithAlign';
        div.appendChild(smithAlign);smithAlign.textContent="Smith-Waterman";
        var freeAlign = document.createElement('button');freeAlign.id='freeAlign';
        div.appendChild(freeAlign);freeAlign.textContent="Alignment-free";
        div.appendChild(document.createElement('hr'));
        // Actions
        demoSeqs.onclick=function(){
            in1.value='TTGAAAGAAAAACAATTTTGGAATCGTATATTAGAATTTGCACAAGAAAGACTGACTCGATCCATGTATGATTTCTATGCTATTCAAGCTGAACTTATCAAGGTAGAGGAAAATGTTGCCACTATATTTCTACGCGGTATTTACAGATGATATCGAAACTGTAGAGACTCGCTCTGAAATGGAAATGGTCTGGGAAAAACAACTAAAAGATATTATTGTAGTAGCTGGTTTTGAAATTTATGACGCTGAAATGATAGCGAACAATATCCACGAATCCAAGAAATTTCAGCAAGCACTCCTTTAATACTTGAAACAAAATTACTCAAGAAAATTATTAATGACTAGCTCACAAGTTGAAGAAGCTACAAATTTAACTCTTTATGACTATAGTCCAAAGTTAGTATCTATTCCTTATTCAGATACGGGATTAAAAGAAAAGTATACCTTTGATAACTTTATTCAAGGGGATGGAAATGTTTGGGCTGTATCAGCCGCTTTAGCTGTCTCTGAAGATTTGGCTCTGACCTATAACCCTCTTTTTATCTATGGAGGACCAGGCCTTGGTAAGACTCACTTATTAAACGCTATTGGAAATGAAATTCTAAAAAATATTCCTAATGCGCGTGTTAAATATATCCCTGCCGAAAGCTTTATTAATGACTTTCTTGATCACCTAAGACTTGGGGAAATGGAAAAGTTTAAAAAGACCTATCGTAGTCTTGATCTTTTGTTAATCGATGATATCCAGTCACTCAGCGGAAAAAAAGTCGCAACTCAGGAAGAATTTTTCAATACCTTTAACGCCCTTCATGACAAGCAAAAACAGATTGTCCTAACGAGTGATCGTAGTCCAAAACATCTAGAAGGGCTCGAGGAGAGGCTTGTCACGCGTTTTAGTTGGGGATTGACACAAACTATCACACCCCCTGACTTTGAAACACGTATTGCCATTTTACAAAGTAAAACGGAACATTTAGGCTACAATTTCCAAAGTGATACTCTAGAATACCTAGCTGGGCAATTTGATTCAAATGTTCGAGATCTTGAGGGAGCCATCAACGACATCACTTTAATTGCCAGAGTAAAAAAAATCAAGGATATCACTATTGATATTGCTGCAGAAGCCATTAGAGCCCGCAAACAAGATGTTAGCCAAATGCTCGTCATCCCAATTGATAAAATCCAAACTGAAGTTGGTAACTTTTATGGTGTTAGTATCAAAGAAATGAAGGGAAGTAGACGCCTTCAAAATATTGTTTTGGCCCGTCAAGTAGCCATGTATTTATCTAGAGAACTAACAGATAATAGTCTTCCAAAAATTGGGAAGGAATTTGGGGGAAAAGATCATACCACAGTCATTCATGCCCATGCCAAAATAAAATCTTTGATTGATCAAGACGATAATTTACGTTTAGAAATTGAATCAATCAAAAAGAAAATCAAATAATTTGTGGATAACTTTTAGTTTTTTATCTTTTTTATCCACATTTTTTAAACAAGCTAAAAAACTTGATAGGACTTGTTTAAAGGCTGTTTTCCACAGATTTCACAGACTCTATTATTACTATTATCTTTCTAATACTAAAAATAAATAAAGGAGAATCCATGATTCATTTTTCAATTAATAAAAATTTATTTCTACAAGCATTAAATATTACTAAGAGAGCTATTAGTTCTAAAAATGCCATTCCTATTTTATCAACTGTCAAAATTGACGTGACCAACGAAGGTGTTACTTTAATTGGTTCAAATGGTCAAATTTCAATTGAAAATTTTATTTCTCAAAAAAATGAAGATGCTGGTTTGTTAATTACTTCTTTAGGTTCGATCCTTCTTGAAGCTTCTTTCTTTATCAATGTAGTATCTAGTTTACCTGATGTAACTCTTGATTTTAAAGAAATTGAA';
            in2.value='CAAAATCAAATTGTTTTGGAATCGTATATTAGAATTTGCACAAGAAAGACTGACTCGGAAAAGATAGCGAACAATATCCACGAATCCAAGAAATTTCAGCAAGCACTCCTTTAATACTTGAAACAAAATTACTCAAGAAAATTATTAATGAAACAGCCTTTGCTGCAAGTACACAAGAGAGTCGTCCGATTTTAACAGGTGTCCACTTCGTATTGAGTCAACACAAAGAGTTAAAAACAGTTGCAACAGACTCTCATCGCCTAAGCCAGAAAAAATTAACTCTTGAAAAAAATAGTGATGATTTTGATGTCGTAATTCCTAGCCGTTCTCTACGCGAATTTTCAGCGGTATTTACAGATGATATCGAAACTGTAGAGATTTTCTTTGCCAATAACCAAATCCTCTTTAGAAGCGAAAATATTAGCTTCTATACTCGTCTCCTAGAAGGAAACTATCCTGATACAGATCGCTTGATTCCAACAGACTTTAACACTACTATTACTTTTAATGTGGTAAACTTACGCCAGTCAATGGAGCGTGCCCGTCTTTTATCAAGTGCGACTCAAAATGGTACTGTGAAACTTGAAATTAAGGATGGGGTTGTTAGCGCCCATGTTCACTCTCCAGAAGTTGGTAAAGTAAACGAAGAAATCGATACTGATCAGGTTACTGGTGAAGATTTGACCATTAGTTTCAACCCAACTTACTTGATTGATTCTCTTAAAGCTTTAAATAGCGAAAAGGTGACCATTAGCTTTATCTCAGCTGTTCGTCCATTTACTCTTGTGCCAGCAGATACTGACGAAGACTTCATGCAGCTCATTACACCAGTTCGTACAAATTAAGTGAAAGAGGTTGAGCCTGGCTCGCCTCTTTTATGATATAATCGGAAAAGAAAAGGAGAGTAGTATGTATCAAGTTGGAAATTTTGTTGAGATGAAAAAACCACACGCTTGTACAATCAAGTCGACTGGTAAAAAGGCTAATCGTTGGGAAATTACACGTGTAGGAGCAGATATCAAAATAAAATGCAGTAATTGTGAGCATGTTGTCATGATGGGGCGATATGATTTTGAGCGAAAAATGAATAAAATTATTGACTGAGAACCCTTAGTTAGAGGGTTAGCACTTTATCCCTTTTTGTGTTATAATATTAGGGATTGAAATGAAAACGGAGAATGAGAAATATGGCTTTGACAGCAGGTATCGTTGGTTTGCCAAACGTTGGTAAATCAACACTATTTAATGCAATTACAAAAGCAGGAGCAGAGGCAGCAAACTACCCATTTGCGACTATTGATCCAAATGTTGGAATGGTGGAAGTTCCAGATGAACGCCTACAAAAACTAACTGAAATGATAACTCCTAAAAAGACAGTTCCCACAACATTTGAATTTACAGATATTGCAGGGATTGTAAAAGGAGCTTCAAAAGGAGAAGGGCTAGGGAATAAATTCTTGGCCAATATTCGTGAAGTAGATGCGATTGTTCACGTAGTTCGTGCTTTTGATGATGAAAATGTAATGCGCGAGCAAGGACGTGAAGACGCCTTTGTAGATCCACTTGCAGATATTGATACAATTAATCTGGAATTAATTCTTGCTGACTTAGAATCAGTGAACAAACGATATGCGCGTGTAGAAAAGATGGCACGTACGCAAAAAGATAAAGAATCAGTAGCAGAATTCAATGTTCTTCAAAAGATTAAACCAGTCCTAGAAGACGGGAAATCAGCTCGTACCATTGAATTTACAGATG'
        }
        smithAlign.onclick=function(){
            4;
        }
        
    }
    
    
    
    // --- INI ---
    this.seqs();
}

